# Configuration for 1D Gaussian with large dataset
ef:
  name: "gaussian_1d"

grid:
  num_train_points: 2000
  num_val_points: 500
  eta_ranges:
    - [-20.0, 20.0]    # eta1 (linear term) - can be any real value
    - [-40.0, -1.0]    # eta2 (quadratic term) - must be negative for integrability

sampling:
  num_samples: 2000     # Number of HMC samples per eta (1000 * 2 eta)
  num_warmup: 400       # Warmup samples
  step_size: 0.1        # HMC step size
  num_integration_steps: 10  # Number of leapfrog steps

optim:
  hidden_sizes: [64, 32, 16]  # Neural network architecture
  activation: "tanh"          # Activation function
  learning_rate: 0.001        # Learning rate
  num_epochs: 100             # Number of training epochs
  batch_size: 64              # Batch size
  seed: 42                    # Random seed

