sampling:
  num_samples: 1500
  num_warmup: 750
  step_size: 0.1
  num_integration_steps: 10
  initial_position: 0.0

model:
  hidden_sizes: [64, 64]
  activation: tanh

optim:
  learning_rate: 0.001
  num_epochs: 50
  batch_size: 64
  seed: 0

ef:
  name: gaussian_1d
  # For multivariate_normal, you could add:
  # x_shape: [3]  # 3-dimensional vectors

grid:
  num_train_points: 256
  num_val_points: 64
  eta_ranges:
    - [-2.0, 2.0]
    - [-1.5, -0.1]


