# Configuration for 3D multivariate Gaussian with large dataset
ef:
  name: "multivariate_normal"
  x_shape: [3]  # 3D multivariate normal

grid:
  num_train_points: 2000
  num_val_points: 500
  eta_ranges:
    - [-20.0, 20.0]    # eta1 (linear terms) - 3D vector, can be any real values
    - [-40.0, -1.0]    # eta2 (matrix terms) - 3x3 matrix, must be symmetric negative definite

sampling:
  num_samples: 2000     # Number of HMC samples per eta (1000 * 2 eta)
  num_warmup: 400       # Warmup samples
  step_size: 0.08        # Smaller step size for higher dimensions
  num_integration_steps: 12  # More integration steps for stability

optim:
  hidden_sizes: [128, 64, 32]  # Larger network for higher dimensional input
  activation: "tanh"           # Activation function
  learning_rate: 0.0008        # Slightly lower learning rate
  num_epochs: 120              # More epochs for complex mapping
  batch_size: 32               # Smaller batch size for higher dimensional data
  seed: 42                     # Random seed