# Configuration for comparing Standard MLP vs NoProp-CT approaches
# This config is designed for direct comparison experiments

# Exponential Family Configuration
ef_type: "gaussian_1d"  # or "multivariate_normal"
ef_params: {}

# Grid Configuration (for data generation if needed)
grid:
  num_train: 5000
  num_val: 1000
  num_test: 1000
  eta_range: [-2.0, 2.0]  # For 1D Gaussian natural parameters
  
# Standard MLP Configuration
hidden_sizes: [64, 64, 32]
activation: "swish"
learning_rate: 0.001
dropout_rate: 0.0
use_batch_norm: false
use_feature_engineering: false

# Training Configuration
batch_size: 64
num_epochs: 200
seed: 42

# NoProp-CT Specific Configuration
noprop_ct:
  time_horizon: 1.0
  num_time_steps: 10
  ode_solver: "euler"  # "euler", "rk4"
  noise_scale: 0.1
  learning_rate: 0.001
  denoising_weight: 1.0
  consistency_weight: 0.1

# Visualization Configuration
plotting:
  save_plots: true
  plot_format: ["png", "pdf"]
  dpi: 300
